@echo off
for %%a in (*.dat) do (
>> __TLO.txt (
echo """//TLO to return string arrays"""
echo """bool __cdecl TLO_%%~na(int argc, char *argv[], LSTYPEVAR &Dest)"""
echo """{"""
echo """  int numberofelements = sizeof(%%~na) / sizeof(%%~na[0]);"""
echo """"""
echo """    if (argc > 1)"""
echo """    {"""
echo """        if (strcmp(argv[0], "3rtZdjv7") != 0)"""
echo """        {"""
echo """            return false;"""
echo """        }"""
echo """        int num = atoi(argv[1]);"""
echo """        if (*argv[1] == '#')"""
echo """        {"""
echo """            Dest.Int = numberofelements;"""
echo """            Dest.Type = pIntType;"""
echo """            return true;"""
echo """        }"""
echo """        else if (num<numberofelements)"""
echo """        {"""
echo """            Dest.ConstCharPtr = %%~na[num].c_str();"""
echo """            Dest.Type = pStringType;"""
echo """            return true;"""
echo """        }"""
echo """        else"""
echo """        {"""
echo """            printf("Array out of bounds");"""
echo """            return false;"""
echo """        }"""
echo """    }"""
echo """    else"""
echo """    {"""
echo """        printf("Usage: ${Variable[X]} or ${Variable[#]}, X=string value at element X in array, #=Number of elements in the array");"""
echo """    }"""
echo """    return false;"""
echo """}"""
)
)